# permissions for end users to edit encryptedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: encryptedsecret-editor-role
rules:
- apiGroups:
  - encryption.take.com
  resources:
  - encryptedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - encryption.take.com
  resources:
  - encryptedsecrets/status
  verbs:
  - get
